# @Author: Mathew Black <Mathew>
# @Date:   2019-11-02T13:43:19-05:00
# @Email:  dev@mathewblack.com
# @Filename: frontend-deployment.yaml
# @Last modified by:   Mathew
# @Last modified time: 2019-11-02T14:29:36-05:00
# @License: MIT
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: react
spec:
  replicas: 2
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: react
    spec:     # pod spec
      containers:
      - name: react
        image: react:v1 # image we pushed
        imagePullPolicy: IfNotPresent
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-client-app-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-client-app
  template:
    metadata:
      labels:
        app: todo-client-app
    spec:
      containers:
      - image: todo-client-kubernetes-app:latest
        name: container1
        imagePullPolicy: IfNotPresent
