apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hodl.fullname" . }}-client-config
  labels:
    app.kubernetes.io/name: {{ include "hodl.name" . }}
    helm.sh/chart: {{ include "hodl.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  default.conf: |-
    server {
      listen 80;
      server_name client;
      root /usr/share/nginx/html;
      autoindex on;
      gzip on;
      gzip_types text/plain application/xml;
      gunzip on;

      location / {
          root   /usr/share/nginx/html;
          try_files $uri /index.html =404;
          index  index.html;
          autoindex on;
      }
    }
