{{- if .Values.ingress.enabled -}}
{{- $fullName := include "hodl.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "hodl.fullname" . }}-ingress
  labels:
    app.kubernetes.io/name: {{ include "hodl.name" . }}
    helm.sh/chart: {{ include "hodl.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
    - hosts:
      {{- range .Values.ingress.tls.hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .Values.ingress.tls.secretName }}
{{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ $fullName }}-client
            servicePort: {{ $.Values.service.client.internalPort }}
        - path: /api
          backend:
            serviceName: {{ $fullName }}-server
            servicePort: {{ $.Values.service.server.internalPort }}
    {{- end }}
{{- end }}
