apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "hodl.fullname" . }}-ingress
  labels:
    app.kubernetes.io/name: {{ include "hodl.name" . }}
    helm.sh/chart: {{ include "hodl.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: hodl.internal
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "hodl.fullname" . }}-client
          servicePort: 80
      - path: /api
        backend:
          serviceName: {{ include "hodl.fullname" . }}-server
          servicePort: 5000
      - path: /stock_api
        backend:
          serviceName: {{ include "hodl.fullname" . }}-stock-server
          servicePort: 4000
