apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hodl.fullname" . }}-stock-server-config
  labels:
    app.kubernetes.io/name: {{ include "hodl.name" . }}
    helm.sh/chart: {{ include "hodl.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  PORT: "{{ .Values.service.stock_server.internalPort }}"
  MONGODB_URL: "mongodb://hodl-mongodb:27017/hodl-exchange"
  BASE_ROUTE: "/stock_api"
